fix(stdlib): Bytes.addStringSlice and Bytes.addBytesSlice
grain-lang/grain pull request #1065
Opened 2021-12-10 06:18 UTC by jozanza

Fixes #1046 

- `Buffer.addStringSlice` appends bytes from the `slice` var returned from an internal call to `String.slice` instead of the original `string`. This prevents unwanted memory access. I was originally going to guard against negative start indexes in `String.slice`, but then I realized we seem to support this behavior because I saw tests for it.
- `Buffer.addBytesSlice` prevents the usage of out-of-bounds `start` and `length` parameters entirely.

2021-12-10 18:58 UTC, phated reviewed
Couple questions about testing

2021-12-10 18:58 UTC, phated commented on compiler/test/stdlib/buffer.test.gr
> +  ("0123456789", -1, 10),
Do we want any tests for positive offsets?

2021-12-10 18:58 UTC, phated commented on compiler/test/stdlib/buffer.test.gr
> +}
Do we want to do this same testing for `addBytesSlice`?

2021-12-10 20:10 UTC, ospencer requested changes
Found one problem but other than that looks good!

2021-12-10 20:10 UTC, ospencer commented on stdlib/buffer.gr
> +  Memory.incRef(WasmI32.fromGrain(String.slice))
I'd probably move this back to the top where it was—the general pattern we've been using is incRefing the function before the arguments.

2021-12-10 20:10 UTC, ospencer commented on stdlib/buffer.gr
> +  let bytelen = WasmI32.load(WasmI32.fromGrain(bytes), 1n)
```suggestion
  let bytelen = WasmI32.load(WasmI32.fromGrain(bytes), 4n)
```

2021-12-11 00:46 UTC, peblair approved these changes
Once the already-existing comments are addressed, this looks good!

2021-12-11 02:05 UTC, ospencer approved these changes

2021-12-11 02:15 UTC, phated approved these changes
Tests pass on a Friday at 7pm, so I 👍 approve

2021-12-11 02:17 UTC, merged