Add a pointer stack for Grain types
grain-lang/grain pull request #1074
Opened 2021-12-11 22:47 UTC by jozanza

Add a new stack for Grain types that are pointers. In theory, this will allow raw wasm i32 pointers to live on the stack and not get GC'ed, which will mean basically zero manual reference counting 🎉

2021-12-11 22:56 UTC, jozanza commented on compiler/src/typed/typed_well_formedness.re
>  };
Great function 10/10

2022-02-27 20:20 UTC, ospencer approved these changes
Hooray! 🥳 🎉

2022-03-03 17:35 UTC, marcusroberts approved these changes
I'm not going to spot bugs, but nice work!

2022-03-03 20:18 UTC, peblair requested changes
I think this is mostly good; just a couple of small comments. Also, as discussed, could you or @ospencer update `memory_management.md` (or whichever file is most appropriate) to document the semantics of `@unsafe`?

2022-03-05 18:45 UTC, ospencer commented on compiler/src/codegen/compcore.re
> +  | [Types.StackAllocated(_)] => arg
That's actually a bug, and an annoying one too 😢 

I'll have it patched in a sec

2022-03-05 19:34 UTC, peblair approved these changes
:shipit:

2022-03-05 21:55 UTC, phated approved these changes
Amazing. Primarily reviewed the code and then skimmed a couple snapshots. Top work @ospencer and @jozanza

2022-03-05 21:55 UTC, phated commented on compiler/src/middle_end/anf_utils.rei
> +let anf_count_vars: anf_expression => (int, int, int, int, int);
I'd love that cleanup in the future.  @ospencer can you add an issue?

2022-03-05 22:00 UTC, ospencer commented on compiler/src/middle_end/anf_utils.rei
> +let anf_count_vars: anf_expression => (int, int, int, int, int);
Got you in #1155

2022-03-06 02:09 UTC, merged