fix(compiler): Refactor WASI polyfill resolution
grain-lang/grain pull request #1261
Opened 2022-05-25 21:51 UTC by ospencer

We previously tried to resolve the location of the wasi polyfill relative to the Grain program being compiled, which is incorrect—it's relative to the directory where `grainc` is invoked.

2022-05-25 22:31 UTC, phated approved these changes
Rebased #1255 on this and it works! Thanks

2022-05-26 16:31 UTC, marcusroberts approved these changes

2022-05-26 16:31 UTC, peblair commented
@ospencer Does this work with `// grainc-flags`?

2022-05-26 16:32 UTC, peblair requested changes
Looks good, but see question in my previous comment before we merge

2022-05-26 16:48 UTC, jozanza approved these changes

2022-05-26 20:57 UTC, ospencer commented
@peblair It has the same limitations as `--stdlib` in that the relative path is relative to the `grain` command being invoked rather than to the file (which is only maybe a limitation depending on how you look at it).

We can't delete that interface since it's still used. We could remove it and refactor the code that uses it, but computing the full path is somewhat expensive vs the times we want to just check if it's defined. I felt like it was fine to keep since we also expose the underlying value for `stdlib_dir` as well.

2022-05-26 20:58 UTC, peblair approved these changes

2022-05-26 21:11 UTC, merged