feat(compiler): Support printing tuple types in oprint
grain-lang/grain pull request #1324
Opened 2022-06-12 20:32 UTC by ospencer

This was crashing the LSP when I wrote `type Tup = (String, String)`. Also noticed it didn't print singleton tuples correctly.

2022-06-12 20:34 UTC, phated approved these changes
Thanks! I'm feeling like making all these NYI was a big mistake on my part 🤦

2022-06-12 20:36 UTC, phated requested changes
Actually, can you add a formatter test?

2022-06-12 20:38 UTC, ospencer commented
@phated I don't think the formatter uses Oprint (and I believe we have tuple tests). Did you mean Graindoc?

2022-06-12 20:40 UTC, phated commented
> Did you mean Graindoc?

No, I didn't. We don't have graindoc tests. I think you are right that the formatter doesn't use oprint (though it should).

I'll switch back to approving this.

2022-06-12 20:41 UTC, phated approved these changes
Please open an issue to write a regression test.

2022-06-13 06:12 UTC, marcusroberts approved these changes

2022-06-13 06:16 UTC, peblair approved these changes

2022-06-13 14:20 UTC, merged