feat(stdlib): Add Number Constants To Number Libarys
grain-lang/grain pull request #1331
Opened 2022-06-13 22:45 UTC by spotandjake

For #1017, adds `Number.pi`, `Number.tau`, `Number.e`, `Float32.pi`, `Float32.tau`, `Float32.e`, `Float64.pi`, `Float64.tau`, `Float64.e`

2022-06-18 11:56 UTC, peblair requested changes
🔥 Thanks, Jake! One minor nitpick, but this is very helpful.

2022-06-18 11:56 UTC, peblair commented on compiler/test/stdlib/float32.test.gr
> +assert e == 2.7182817f
@spotandjake can you add the newlines at the end of these test files?

2022-06-21 19:57 UTC, ospencer requested changes
I noticed that the value for tau might have been copied and pasted from pi, so I updated that here. Also, since `Number` uses f64s under the hood, I updated pi, tau, and e to be the higher precision variants 😄

2022-06-21 19:57 UTC, ospencer commented on compiler/test/stdlib/float32.test.gr
> +assert tau == 3.1415927f
```suggestion
assert tau == 6.2831853f
```

2022-06-21 19:57 UTC, ospencer commented on compiler/test/stdlib/float64.test.gr
> +assert tau == 3.141592653589793d
```suggestion
assert tau == 6.283185307179586d
```

2022-06-21 19:57 UTC, ospencer commented on compiler/test/stdlib/number.test.gr
> +assert Number.tau == 3.1415927
```suggestion
assert Number.tau == 6.283185307179586
```

2022-06-21 19:57 UTC, ospencer commented on compiler/test/stdlib/number.test.gr
> +assert Number.pi == 3.1415927
```suggestion
assert Number.pi == 3.141592653589793
```

2022-06-21 19:57 UTC, ospencer commented on stdlib/float32.gr
> +export let tau = 3.1415927f
```suggestion
export let tau = 6.2831853f
```

2022-06-21 19:57 UTC, ospencer commented on stdlib/float32.gr
> + * PI represented as a Float32 value.
```suggestion
 * Pi represented as a Float32 value.
```

2022-06-21 19:57 UTC, ospencer commented on stdlib/float32.gr
> + * TAU represented as a Float32 value.
```suggestion
 * Tau represented as a Float32 value.
```

2022-06-21 19:57 UTC, ospencer commented on stdlib/float32.gr
> + * Eulers Number represented as a Float32 value.
```suggestion
 * Euler's number represented as a Float32 value.
```

2022-06-21 19:57 UTC, ospencer commented on stdlib/float64.gr
> + * PI represented as a Float64 value.
```suggestion
 * Pi represented as a Float64 value.
```

2022-06-21 19:57 UTC, ospencer commented on stdlib/float64.gr
> + * TAU represented as a Float64 value.
```suggestion
 * Tau represented as a Float64 value.
```

2022-06-21 19:57 UTC, ospencer commented on stdlib/float64.gr
> +export let tau = 3.141592653589793d
```suggestion
export let tau = 6.283185307179586d
```

2022-06-21 19:57 UTC, ospencer commented on stdlib/float64.gr
> + * Eulers Number represented as a Float64 value.
```suggestion
 * Euler's number represented as a Float64 value.
```

2022-06-21 19:57 UTC, ospencer commented on stdlib/number.gr
> + * PI represented as a Number value.
```suggestion
 * Pi represented as a Number value.
```

2022-06-21 19:57 UTC, ospencer commented on stdlib/number.gr
> +export let tau = 3.1415927
```suggestion
export let tau = 6.283185307179586
```

2022-06-21 19:57 UTC, ospencer commented on stdlib/number.gr
> + * TAU represented as a Number value.
```suggestion
 * Tau represented as a Number value.
```

2022-06-21 19:57 UTC, ospencer commented on stdlib/number.gr
> +export let pi = 3.1415927
```suggestion
export let pi = 3.141592653589793
```

2022-06-21 19:57 UTC, ospencer commented on stdlib/number.gr
> + * Eulers Number represented as a Number value.
```suggestion
 * Euler's number represented as a Number value.
```

2022-06-21 19:57 UTC, ospencer commented on compiler/test/stdlib/number.test.gr
> +assert Number.e == 2.7182817
```suggestion
assert Number.e == 2.718281828459045
```

2022-06-21 19:57 UTC, ospencer commented on stdlib/number.gr
> +export let e = 2.7182817
```suggestion
export let e = 2.718281828459045
```

2022-06-21 19:59 UTC, spotandjake commented on compiler/test/stdlib/float32.test.gr
> +assert tau == 3.1415927f
oops

2022-06-21 21:27 UTC, ospencer approved these changes
Great work @spotandjake!

2022-06-22 16:39 UTC, merged