feat(stdlib): Add String.lastIndexOf
grain-lang/grain pull request #1372
Opened 2022-07-26 21:41 UTC by spotandjake

This pr adds String.lastIndexOf, it works the same as indexOf but instead of returning the first occurance of the search it returns the last.

2022-07-31 17:16 UTC, ospencer requested changes
I think what might be a bit better here is reusing the code from `indexOf`. The only difference between the two would be the `break` line in the loop.

You can turn `indexOf` into a helper function that takes an additional argument, maybe called `findFirst`, and then that `if` becomes
```
      if (Memory.compare(ptr, pptr, psize) == 0n) {
        result = idx
        if (findFirst) break
      }
```
And then you can call the helper for both functions:
```
export let indexOf = (search, string) => {
  indexOf(search, string, true)
}
export let lastIndexOf = (search, string) => {
  indexOf(search, string, false)
}

2022-07-31 17:18 UTC, spotandjake commented on .gitignore
> +yarn.lock
> I think what might be a bit better here is reusing the code from `indexOf`. The only difference between the two would be the `break` line in the loop.
> 
> You can turn `indexOf` into a helper function that takes an additional argument, maybe called `findFirst`, and then that `if` becomes
> 
> ```
>       if (Memory.compare(ptr, pptr, psize) == 0n) {
>         result = idx
>         if (findFirst) break
>       }
> ```
> 
> And then you can call the helper for both functions:
> 
> ```
> export let indexOf = (search, string) => {
>   indexOf(search, string, true)
> }
> export let lastIndexOf = (search, string) => {
>   indexOf(search, string, false)
> }
> ```

I thought about that but won't that be extremely slow on long strings compared to what I am doing.

2022-07-31 17:26 UTC, ospencer commented on .gitignore
> +yarn.lock
Oh I hadn't realized you actually made it iterate backwards.

2022-07-31 17:44 UTC, spotandjake commented on .gitignore
> +yarn.lock
Yup why the check for incrementing the index is different, I  pretty sure my logic is sound and the tests pass but you might want to double check the index increment and make sure the check makes sense.

2022-07-31 18:21 UTC, ospencer requested changes
I left some suggestions here—I switched up the logic a bit to avoid a `Memory.compare` when we're not at the start of a valid codepoint.

2022-07-31 18:21 UTC, ospencer commented on stdlib/string.gr
> +      // Compare The Current String Section To The Search String
```suggestion
      let byte = WasmI32.load8U(stringPtr, 0n)
      stringPtr -= 1n
      if ((byte & 0xC0n) == 0x80n) {
        // We're not at the start of a codepoint, so move on
        continue
      }
      
```

2022-07-31 18:21 UTC, ospencer commented on stdlib/string.gr
> +        // If They Are Equal Then Save The Index
```suggestion
```

2022-07-31 18:21 UTC, ospencer commented on stdlib/string.gr
> +      }
```suggestion
      stringIndex -= 1n
```

2022-07-31 18:21 UTC, ospencer commented on stdlib/string.gr
> +      stringPtr = WasmI32.sub(stringPtr, 1n)
```suggestion
```

2022-07-31 18:21 UTC, ospencer commented on stdlib/string.gr
> +    let mut stringIndex = 0n
You'll need to import `untagSimpleNumber` for this one.
```suggestion
    let mut stringIndex = untagSimpleNumber(lastIndex)
```

2022-07-31 18:21 UTC, ospencer commented on stdlib/string.gr
> +      Some(strLen - tagSimpleNumber(matchIndex))
```suggestion
      Some(tagSimpleNumber(matchIndex))
```

2022-07-31 19:57 UTC, ospencer commented on stdlib/string.gr
> +  let lastIndex = length(string) - length(search)
```suggestion
  let lastIndex = length(string) - length(search)
  
```

2022-07-31 19:57 UTC, ospencer commented on stdlib/string.gr
> +  let (&) = WasmI32.and
```suggestion
  let (&) = WasmI32.and
  
```

2022-07-31 19:57 UTC, ospencer commented on stdlib/string.gr
> +    // Return The Result
```suggestion

```

2022-07-31 19:59 UTC, ospencer approved these changes
Great work!

2022-08-01 15:22 UTC, ospencer commented
Looks like you need to regenerate the Graindocs.

2022-08-01 17:40 UTC, phated requested changes
I'm holding off my review until #1389 lands because this PR contains a bunch of formatting that shouldn't be included in the PR

2022-08-02 01:18 UTC, spotandjake commented
> Looks like you need to regenerate the Graindocs.

GrainDoc Seems To Be Up To Date

2022-08-04 19:18 UTC, phated commented on compiler/test/stdlib/string.test.gr
> +
```suggestion
```

2022-08-04 19:23 UTC, phated approved these changes
Really cool! I like that you are diving into the low-level Grain stuff @spotandjake 🎉

2022-08-04 19:25 UTC, spotandjake commented
> Really cool! I like that you are diving into the low-level Grain stuff @spotandjake 🎉

Thank you, after working on my linker I have needed to work with a lot more low level grain stuff and realized it is actually quite friendly and easier to work with.

2022-08-04 20:10 UTC, merged