feat(compiler)!: Early return
grain-lang/grain pull request #1464
Opened 2022-10-31 16:54 UTC by ospencer

Closes #553 

This PR implements the ability to return early from a function in Grain using the `return` keyword. Here's an example of how this might be used:

```
import Array from "array"

let findFour = arr => {
  for (let mut i = 0; i < Array.length(arr); i += 1) {
    if (arr[i] == 4) {
      return Some(4)
    }
  }

  return None
}
```

`return` in Grain works similarly to other languages with `return`, with one exception: while Grain functions return the value of the last expression implicitly, if a `return` statement is used within a function, _all_ values returned from the function must be made explicit.

This may seem like a stylistic choice, but we felt it was important to properly fit this feature into the language. Some error messages may become confusing if all returns aren't made explicit. For example, look at the code below:

![image](https://user-images.githubusercontent.com/7244034/199061016-79c12735-c0ff-41a0-ae23-a712b1018704.png)

It's reasonable to see that this should be a type error. However, when one attempts to explain _exactly why_ this is a type error, it's not obvious. (If you'd like to try to figure it out for yourself, do so now, as the next line will explain.)

The nearest cousin to `return` in terms of how it fits into the language is `throw` or `fail`, and just like `throw` or `fail`, `return` has an "any" type. This is to appease the typechecker—you'll want to place one of these statements just about anywhere in your code, and if using one of these statements typechecked to `Void`, wherever you used it would _also_ have to typecheck to `Void`, and this would be frustrating when trying to throw an error in a single case of a `match` statement, or even a branch of an `if` statement.

Because of `return`'s "any" type, the entire `if` typechecks to `Number` because of the `else` branch. However, the `if` is in the final position of the function body, so it (would be) implicitly returned, which means the `if` must typecheck to `String`, because of the `return` statement which declares the return type of the function to `String`, which in turn means that the `else` branch must also be `String`.

We feel that's a lot of mental hoops to jump through! What's far simpler is an error message that tells you that you need to add a return statement in the `else` branch (or on the whole `if`), and then it's obvious why the types don't line up.

This is why we made the decision to require all returns be explicit if a `return` statement is used. 🙂

2022-10-31 17:49 UTC, phated requested changes
SoOoOoOo excited for this feature. Really easy to follow implementation too ❤️ 

One question and one request (I think we should have some formatter input/output tests).

2022-10-31 17:49 UTC, phated commented on compiler/src/formatting/format.re
> +      ])
Need some tests for this?

2022-10-31 17:49 UTC, phated commented on compiler/test/suites/returns.re
> +describe("early return", ({test, testSkip}) => {
Do we not want any snapshot tests for this?

2022-10-31 22:47 UTC, ospencer commented
@phated Added those tests.

2022-11-04 18:06 UTC, phated approved these changes
Delightful!

2023-01-11 05:07 UTC, merged