feat(compiler)!: Implement `Infinity` and `NaN` syntax
grain-lang/grain pull request #1472
Opened 2022-11-08 00:50 UTC by spotandjake

This pr implement `Infinity` and `NaN` syntax as I was talking about in dms with Oscar.

Closes: #693

2022-11-08 00:56 UTC, ospencer requested changes
Looking good! Can you make an issue on the lsp repo to add syntax highlighting for this?

2022-11-08 00:56 UTC, ospencer commented on compiler/src/parsing/lexer.re
> +  ("Infinity" | "NaN")
Just to make this slightly cleaner, I'd make a `dec_float_alphabetic` that's just this, and then reference it here.

2022-11-08 00:56 UTC, ospencer commented on compiler/test/__snapshots__/basic_functionality.4d1501b9.0.snapshot
> +        (f64.const nan:0x8000000000000)
Can't argue with that.

2022-11-08 00:56 UTC, ospencer commented on compiler/test/__snapshots__/basic_functionality.6599e10c.0.snapshot
> +        (f64.const -inf)
The wat syntax for these is pretty nice!

2022-11-08 00:56 UTC, ospencer commented on compiler/test/suites/basic_functionality.re
> +  assertSnapshot("neginf", "let x = -Infinity; x");
```suggestion
  assertSnapshot("infinity_neg", "let x = -Infinity; x");
```

2022-11-08 00:56 UTC, ospencer commented on compiler/test/suites/basic_functionality.re
> +  assertSnapshot("inf", "let x = Infinity; x");
```suggestion
  assertSnapshot("infinity", "let x = Infinity; x");
```

2022-11-08 01:03 UTC, spotandjake commented
Applied Those Changes

2022-11-08 01:25 UTC, ospencer commented
You'll have to regen the snapshots.

2022-11-08 01:25 UTC, spotandjake commented
> You'll have to regen the snapshots.

I did?

2022-11-08 01:40 UTC, ospencer commented
After accepting the suggestions, since we changed the names of the tests.

2022-11-08 01:41 UTC, spotandjake commented
> After accepting the suggestions, since we changed the names of the tests.

yah I did in my commit for it the test are updated

2022-12-03 18:30 UTC, ospencer approved these changes
Looks great!

2023-01-11 19:24 UTC, spotandjake commented
Rebased on main, and the tests the tests seem to be passing now.

2023-01-11 20:42 UTC, merged