feat(stdlib): Mutable queue and stack
grain-lang/grain pull request #1479
Opened 2022-11-12 22:50 UTC by alex-snezhko

Mutable array-based implementations for queues and stacks. From a few benchmarks these implementations offer much faster performance than the current immutable `Queue` and `Stack` implementations (likely due to gains in cache locality because of underlying array representation), which may make them more viable for performance-sensitive applications.

2022-11-30 23:37 UTC, phated commented
@alex-snezhko I think we're going to hold this PR back from 0.5.5 because we think it is confusing to have Queue and Stack be the immutable versions but Map & Set are mutable (and then have the inverse have the special naming). We're going to deprecated the immutable Queue & Stack in 0.5.5 and then have you make this the breaking change that moves stuff around.

How does that sound?

2022-12-01 06:13 UTC, alex-snezhko commented
Sounds good!

2022-12-03 10:35 UTC, marcusroberts approved these changes
Easy to read and clear code, great documentation and tests.

Looks very good to me!

2023-01-31 01:37 UTC, alex-snezhko commented
#1644 and #1621 should probably be resolved before merging this

2023-02-20 01:17 UTC, phated commented on compiler/test/stdlib/immutablestack.test.gr
> +import Stack from "immutablestack"
Is this file going away since they are in the same file now?

2023-02-20 01:22 UTC, phated requested changes
@alex-snezhko I've rebased this so I could generate the docs with my submodule support in #1684 - however, I think you need to update the `@since` and `@history` for the various things that moved around. e.g. Since functions moved from the root into the `Immutable` submodule, I think those should be `@since v0.6.0` with a history item saying they were originally a root API (similar to how we did those other PRs).

2023-02-21 23:51 UTC, phated commented
Rebased again and regenerated the docs with graindoc fixes.

2023-02-22 00:15 UTC, ospencer reviewed
Overall looks great! Would just love if these record fields were renamed.

2023-02-22 00:15 UTC, ospencer commented on stdlib/queue.gr
> +  mut tailI: Number, // tail points to where the next element should be inserted
Can we call these `headIndex` and `tailIndex`?

2023-02-22 00:17 UTC, ospencer commented
Also looks like the set tests need to be formatted.

2023-02-22 03:08 UTC, phated approved these changes
I made the change Oscar wanted, so this should be good to queue.

2023-02-22 03:38 UTC, alex-snezhko commented
Thanks @phated :)

2023-02-22 03:38 UTC, merged