feat(stdlib): Improve perf for array flatMap, array & list some & every
grain-lang/grain pull request #1487
Opened 2022-11-22 23:42 UTC by alex-snezhko

Improves `Array.flatMap` performance addressing #458. Also small performance upgrade for `every` and `some` for `Array` and `List`, as I noticed that in their current state they would always traverse the entire collection even after a suitable match/counterexample was found.

2022-11-23 21:54 UTC, phated approved these changes
Looks great! Thanks for cleaning these up.

2022-11-24 18:21 UTC, ospencer requested changes
The array functions look great! The list functions aren't tail-recursive anymore, but they need to be.

2022-11-25 02:56 UTC, alex-snezhko commented
@ospencer I was hesitant about this initially as well, but I think these implementations are actually tail recursive because of the short-circuiting of `&&` and `||`. It also looks like the wasm generated by these implementations is the same as implementations that are more evidently tail-recursive.

2022-11-28 18:43 UTC, ospencer reviewed
I was the one who implemented `&&` and `||` and completely forgot that these are essentially freebies when it comes to tail calls. Hah. Of course, it's not obvious that it's tail recursive. I'm going to drop some comments in there so we don't forget, and this is good to go.

2022-11-28 18:45 UTC, ospencer commented on stdlib/list.gr
> +    [first, ...rest] => fn(first) && every(fn, rest),
```suggestion
    // The short-circuiting of `&&` makes this tail-recursive
    [first, ...rest] => fn(first) && every(fn, rest),
```

2022-11-28 18:45 UTC, ospencer commented on stdlib/list.gr
> +    [first, ...rest] => fn(first) || some(fn, rest),
```suggestion
    // The short-circuiting of `||` makes this tail-recursive
    [first, ...rest] => fn(first) || some(fn, rest),
```

2022-11-28 18:45 UTC, ospencer approved these changes
Thanks @alex-snezhko!

2022-11-29 00:14 UTC, merged