Generate new examples stdlib array
grain-lang/grain pull request #1692
Opened 2023-02-21 21:28 UTC by mahSource

Updated `Array.set`, `Array.sort`, and `Array.rotate` to working multi-line examples.

2023-02-21 21:34 UTC, ospencer requested changes

2023-02-21 21:34 UTC, ospencer commented on stdlib/array.gr
> + * assert arr == [> 1, 9, 3, 4, 5]
```suggestion
 * let array = [> 1, 2, 3, 4, 5] 
 * Array.set(1, 9, array)
 * assert array == [> 1, 9, 3, 4, 5]
```

2023-02-21 21:34 UTC, ospencer commented on stdlib/array.gr
> + * assert arr == [>1,2,3]
```suggestion
 * let array = [> 3, 2, 1]
 * Array.sort(compare, array)
 * assert array == [> 1, 2, 3]
```

2023-02-21 21:34 UTC, ospencer commented on stdlib/array.gr
> + * assert arr == [>1,2,3]
This could be a good time to have one example using `compare` and another using a custom comparator.

2023-02-21 21:34 UTC, ospencer commented on stdlib/array.gr
> + * assert arr == [> 4, 5, 1, 2, 3]
```suggestion
 * let array = [> 1, 2, 3, 4, 5]
 * Array.rotate(2, array)
 * assert array == [> 4, 5, 1, 2, 3]
```

2023-02-21 21:34 UTC, ospencer commented on stdlib/array.gr
> + * assert arr == [> 2, 3, 4, 5, 1]
```suggestion
 * let array = [> 1, 2, 3, 4, 5]
 * Array.rotate(-1, array)
 * assert array == [> 2, 3, 4, 5, 1]
```

2023-02-22 02:22 UTC, phated reviewed
Just one nit.

2023-02-22 02:22 UTC, phated commented on stdlib/array.gr
> + * @example
```suggestion
 *
 * @example
```
I think we should try to have visual space between examples and the params

2023-02-27 01:53 UTC, closed without merging

2023-02-27 01:53 UTC, mahSource commented
.