feat: Add `toIntegerRatio` and `fromIntegerRatio`  to Rational Library
grain-lang/grain pull request #1746
Opened 2023-03-12 22:13 UTC by spotandjake

This adds `toIntegerRation` and `fromIntegerRation`, to the `rational` library.

This doesnt close #1672, but it adds a few of the functions for it.

2023-03-18 21:04 UTC, alex-snezhko commented on stdlib/rational.gr
> +  fromNumber(numerator / denominator)
I think this should throw an exception if the inputs are not integers

2023-03-28 13:06 UTC, spotandjake commented on stdlib/rational.gr
> +provide let toIntegerRatio = (x: Rational) => {
nope

2023-04-08 14:04 UTC, ospencer commented on stdlib/rational.gr
> + * @param x: The rational to convert
Something like this maybe?
```suggestion
 * @param x: The rational to split
```

2023-04-08 14:04 UTC, ospencer commented on stdlib/rational.gr
> + * @returns The built rational
```suggestion
 * @returns The newly constructed rational
```

2023-04-15 21:58 UTC, phated requested changes
Needs a few more changes.

2023-04-15 21:58 UTC, phated commented on stdlib/rational.gr
> + * Gets the numerator and denominator of the rational as a tuple.
```suggestion
 * Gets the numerator and denominator of the rational.
```
The return type is specified in the table

2023-04-15 21:58 UTC, phated commented on stdlib/rational.gr
> + * @throws InvalidArgument(String): If the numerator or denominator are not integers
Split this into two throws "if the numerator is not an integer" and "if the denominator is not an integer"

2023-04-15 21:58 UTC, phated commented on stdlib/rational.gr
> + * @returns The newly constructed rational
```suggestion
 * @returns The reduced rational 
```

2023-04-15 21:58 UTC, phated commented on stdlib/rational.gr
> +  }
Separate this throw saying which one is the problem

2023-04-16 23:16 UTC, phated approved these changes
Excellent!

2023-04-17 00:52 UTC, merged