feat(compiler): Reduce size of runtime heap
grain-lang/grain pull request #1807
Opened 2023-04-07 00:22 UTC by ospencer

Since #1410 was landed, far less memory is used in programs run in runtime mode. I did an audit, and it seems that we now only use ~650 bytes, so I reduced the reserved runtime size from 16384 bytes down to 2048 bytes. This is helpful when running in some memory-constrained runtimes, like wasm4.

2023-04-07 00:22 UTC, ospencer commented
I considered going down to 1024 bytes, but I wanted to leave some breathing room.

2023-04-07 00:42 UTC, spotandjake approved these changes
Looks good less memory usage should defs help with targets like wasm4

2023-04-07 17:54 UTC, phated requested changes
Docs

2023-04-07 17:54 UTC, phated commented on stdlib/runtime/malloc.gr
> +provide let _RESERVED_RUNTIME_SPACE = 0x800n
I believe the docs need to be updated? They say we reserve a quarter page.

2023-04-12 22:28 UTC, peblair approved these changes
Looks good, modulo @phated's comment about docs. Tossing an approval on here so that it's ready to go once that's addressed.

2023-04-22 20:58 UTC, phated commented on stdlib/runtime/malloc.gr
> +provide let _RESERVED_RUNTIME_SPACE = 0x800n
I just did this

2023-04-22 20:59 UTC, phated approved these changes

2023-04-22 22:19 UTC, merged