feat(stdlib)!: Adjust `List.insert` param order
grain-lang/grain pull request #1857
Opened 2023-06-12 04:22 UTC by alex-snezhko

Closes #1856

2023-06-12 04:23 UTC, spotandjake approved these changes
Looks good, though you forgot to regain the grain doc.

2023-06-12 16:14 UTC, jozanza approved these changes
I'm cool with this

2023-06-12 16:24 UTC, peblair approved these changes

2023-06-12 16:30 UTC, marcusroberts approved these changes

2023-06-12 16:38 UTC, ospencer approved these changes

2023-06-25 22:17 UTC, phated requested changes
This needs a history entry

2023-06-30 23:59 UTC, phated approved these changes

2023-07-01 01:02 UTC, merged