chore(stdlib)!: Switch to using records for `getInternalStats`
grain-lang/grain pull request #1898
Opened 2023-07-22 21:39 UTC by spotandjake

This cleans up some todos left over from #190 being closed, and switches `getInternalStats` from returning a tuple to a record.

This is marked as breaking as we change the signature of `getInternalStats`

2023-07-22 21:57 UTC, spotandjake commented
Looks like one of the provides snapshots gets updated because of a dependency on the stdlib

2023-08-18 20:04 UTC, peblair approved these changes
Looks good!

2023-08-20 00:15 UTC, phated requested changes
Most notable problem is naming of the record in set

2023-08-20 00:15 UTC, phated commented on compiler/test/stdlib/map.test.gr
>  // (nodeCount, bucketLength)
These comments don't make sense anymore

2023-08-20 00:15 UTC, phated commented on compiler/test/stdlib/set.test.gr
>  // (nodeCount, bucketLength)
Same as above

2023-08-20 00:15 UTC, phated commented on stdlib/set.gr
> +provide record InternalMapStats {
These are `Set` stats not `Map` stats

2023-08-20 00:15 UTC, phated commented on stdlib/set.gr
> + * @history v0.6.0: switch to returning `InternalMapStats` record
Same as above

2023-08-20 16:21 UTC, spotandjake commented
All Fixed

2023-08-20 19:33 UTC, phated requested changes
Light rewording on the `@history` attributes

2023-08-20 19:33 UTC, phated commented on stdlib/set.gr
> + * @history v0.6.0: switch to returning `InternalSetStats` record
```suggestion
 * @history v0.6.0: Return `InternalSetStats` record instead of a tuple
```

2023-08-20 19:33 UTC, phated commented on stdlib/map.gr
> + * @history v0.6.0: switch to returning `InternalMapStats` record
```suggestion
 * @history v0.6.0: Return `InternalMapStats` record instead of a tuple
```

2023-08-20 19:40 UTC, phated approved these changes

2023-08-20 22:05 UTC, merged