feat(stdlib): Add ASCII utilities to string, char
grain-lang/grain pull request #1975
Opened 2024-01-23 05:33 UTC by alex-snezhko

Add ASCII utilities to `String` and `Char` modules

2024-01-23 05:38 UTC, spotandjake reviewed
This looks good to me. Just needs docs generated.

2024-01-23 05:40 UTC, alex-snezhko commented
Generated

2024-01-23 05:41 UTC, spotandjake approved these changes

2024-01-23 06:29 UTC, ospencer commented on stdlib/char.gr
> + * Checks if the character is a digit.
```suggestion
 * Checks if the character is an ASCII digit.
```

2024-01-23 06:29 UTC, ospencer commented on stdlib/char.gr
> + * @returns `true` if the character is a digit or `false` otherwise
```suggestion
 * @returns `true` if the character is an ASCII digit or `false` otherwise
```

2024-01-26 18:30 UTC, ospencer approved these changes

2024-01-27 22:23 UTC, phated requested changes
Doc comments and one test, but otherwise looks good

2024-01-27 22:23 UTC, phated commented on compiler/test/stdlib/char.test.gr
> +assert !Char.isAsciiAlpha('🌾')
These are the ascii digit tests according to the comment

2024-01-27 22:23 UTC, phated commented on stdlib/char.gr
> + * @param char: The character
We generally write these like: "The character to check"

2024-01-27 22:23 UTC, phated commented on stdlib/char.gr
> + * @param char: The character
See above

2024-01-27 22:23 UTC, phated commented on stdlib/char.gr
> + * @param char: The character
"The character to convert"?

"The character to transform"?

2024-01-27 22:23 UTC, phated commented on stdlib/char.gr
> + * @param char: The character
See above

2024-01-27 22:23 UTC, phated commented on stdlib/string.gr
> + * @param string: The string
See previous comments

2024-01-27 22:23 UTC, phated commented on stdlib/string.gr
> + * @param string: The string
See previous comments

2024-01-27 22:35 UTC, phated commented
Needs regen too, I think

2024-01-27 22:49 UTC, phated approved these changes

2024-01-28 00:11 UTC, merged