Print constants when we are able
grain-lang/grain pull request #2009
Opened 2024-02-10 22:43 UTC by phated

This changes `print_constant` to print constants via the formatter when we have values that are easy to print. We could probably print strings/chars/bytes but I couldn't figure out how to escape the values correctly in `print_constant` so I made them separate pattern matches that get the original source.

We will be able to make the `print_constant` function **a lot** nicer when we complete the TODOs but that's out of scope for the current formatter changes.

2024-02-10 22:43 UTC, phated commented on compiler/test/grainfmt/binops.expected.gr
> +let y1 = 1 + 2/3
These expected were the primary goal of the change.

2024-02-11 15:58 UTC, ospencer requested changes

2024-02-11 15:58 UTC, ospencer commented on compiler/src/formatting/fmt.re
> +      string(numerator) ++ string("/") ++ string(denominator)
This does not handle comments. You either need full locations on the individual components to be able to capture any comments (and determine if they're before or after the slash) or you need the original code.

2024-02-19 18:32 UTC, ospencer approved these changes
Great work! This looks good to go to me.

2024-02-19 18:33 UTC, merged