chore(stdlib): Improve Float32 Docs
grain-lang/grain pull request #2012
Opened 2024-02-13 01:34 UTC by spotandjake

This improves the docs in the `Float32` module, It adds examples for the float32 syntax to the top following the pattern ive been using in other libs, Adds example to all the functions. and updates the documentation for `Float32.infinity` and `Float32.nan` to mention the alternative syntax.

2024-02-17 21:26 UTC, alex-snezhko approved these changes

2024-02-19 00:37 UTC, phated requested changes
Same as the other PR

2024-02-19 00:37 UTC, phated commented on stdlib/float32.gr
> + * This is equivalent to `Infinityf`.
```suggestion
 * This is an alternative to the `Infinityf` literal.
```

2024-02-19 00:37 UTC, phated commented on stdlib/float32.gr
> + * This is equivalent to `NaNf`.
```suggestion
 * This is an alternative to the `NaNf` literal.
```

NaN is not equivalent to NaN

2024-02-19 00:45 UTC, spotandjake commented
Made those changes

2024-02-20 15:36 UTC, phated approved these changes

2024-02-20 16:24 UTC, merged