chore(stdlib): Improve `Float64` docs
grain-lang/grain pull request #2013
Opened 2024-02-13 01:40 UTC by spotandjake

This improves the docs in the `Float64` module, It adds examples for the float64 syntax to the top following the pattern ive been using in other libs, Adds example to all the functions. and updates the documentation for `Float64.infinity` and `Float64.nan` to mention the alternative syntax.

2024-02-17 21:26 UTC, alex-snezhko approved these changes

2024-02-19 00:35 UTC, phated requested changes
A little rewording

2024-02-19 00:35 UTC, phated commented on stdlib/float64.gr
> + * This is equivalent to `Infinityd`.
```suggestion
 * This is an alternative to the `Infinityd` literal.
```

2024-02-19 00:35 UTC, phated commented on stdlib/float64.gr
> + * This is equivalent to `NaNd`.
```suggestion
 * This is an alternative to the `NaNd` literal.
```

NaN is not equivalent to NaN

2024-02-19 00:44 UTC, spotandjake commented
Made those changes

2024-02-20 15:36 UTC, phated approved these changes

2024-02-20 16:24 UTC, merged