fix(stdlib): Avoid WASI random_get in Hash stdlib during module startup
grain-lang/grain pull request #2078
Opened 2024-03-25 22:50 UTC by ospencer

2024-03-25 22:55 UTC, spotandjake requested changes
Looks great, I think we need to add some the exception that could occur to grain doc but otherwise lets get this merged.

2024-03-25 22:55 UTC, spotandjake commented on stdlib/hash.gr
>   */
We should add the exception that `Result.unwrap` would throw to the grain doc to make sure it's known about.

2024-03-26 00:32 UTC, ospencer commented
@spotandjake done.

2024-03-26 00:33 UTC, spotandjake approved these changes
Looks great.

2024-03-26 00:45 UTC, spotandjake commented
It does look like before this gets merged the grain doc is going to need to be regenerated.

2024-03-26 08:37 UTC, marcusroberts approved these changes
Looks good to me!

2024-03-28 21:54 UTC, merged