Add string concatenation to Pervasives
grain-lang/grain pull request #280
Opened 2020-09-06 22:26 UTC by ospencer

This adds string concatenation to Pervasives, which allows the user to concatenate strings without having to import/depend on the String library.

```grain
'Hello' ++ ', world'
```

As I mentioned in Discord, I'm not 100% sold on this syntax since with `let mut` we might want to have the `++` and `--` operators for use with numbers, and there's some potential ambiguous syntax if string concatenation also uses `++`.

We _also_ don't quite have the ability to use `^` like OCaml does, since we use that syntax for unboxing. (I also mentioned in Discord that I'm more or less okay with removing/changing the syntax for unboxing, since it's a lot less common now that we have `let mut`.)

Open to ideas for new syntax or another path forward; also fine just merging this and worrying about it when we actually want to support `++` and `--` for use with numbers.

Closes #279.

2020-09-06 22:26 UTC, ospencer commented on compiler/src/codegen/compcore.re
> +let swap_slots_i32 = [|Type.int32, Type.int32, Type.int32|];
This seems fine since Binaryen will optimize away the unused slots.

2020-09-08 06:17 UTC, phated approved these changes
💯 💯 💯 💯 Love this!

I'm actually not a fan of `++` or `--` for incr/decr on mutable values because it is awkward for usage on mutable record properties, so I'm happy to use `++` for string concatenation.

2020-09-08 08:00 UTC, belph requested changes
This is great! 

Before merging, though, I would to discuss why this was added as a mashtree implementation as opposed to a stdlib function. In my numbers branch, I am moving more in favor of cleaning up compcore.re such that it delegates out anything more complex than malloc (and sometimes even that) to appropriate stdlib functions. My understanding is that Binaryen should have our back in terms of inlining where appropriate (maybe that's wrong, though?).

@ospencer How would you feel about making this a function instead (even if there is hard-coded syntax, it the `compile_prim2` implementation could call the function)?

2020-09-08 12:52 UTC, ospencer commented
Summary from chat outside GH: this was removed as a stdlib function and built into the compiler to avoid Pervasives depending on another library/wasm file, which in the browser results in an extra network call or natively an extra disk read for *every* Grain program, regardless of your use of the `++` function. We plan to start offloading much of the runtime from JS to wasm anyway, so we figured we could start that effort now to avoid bloating `compcore.re` even more. 

#282 to track. This PR adds a set of runtime imports and imports the concat function from there.

@belph ready for you to take another look.

2020-09-08 13:01 UTC, belph approved these changes
Looks great. Thanks for the change!

2020-09-08 13:03 UTC, merged