Support floats without a leading integral part
grain-lang/grain pull request #341
Opened 2020-09-29 02:53 UTC by ospencer

Adds the ability to write `.5` instead of `0.5`.

2020-09-29 13:59 UTC, peblair requested changes
LGTM; just one comment

2020-09-29 13:59 UTC, peblair commented on compiler/test/test_end_to_end.re
> +  t("number_syntax4", "1.2d", "1.2"),
I'd like to see a parser test for just `.` before we merge this (I know it should pass, but I think it's appropriate)

2020-09-30 14:15 UTC, ospencer commented
@peblair Added.

2020-09-30 14:16 UTC, peblair approved these changes

2020-10-01 16:11 UTC, merged