Add Queue to stdlib
grain-lang/grain pull request #371
Opened 2020-10-04 20:31 UTC by miguelcarvalho13

Closes #363 

Adds a Queue library to the `stdlib`.

2020-10-04 21:50 UTC, ospencer reviewed
This looks fantastic!!

How would you feel about having the Empty queue just be `{ forwards: [], backwards: [] }`? The `dequeue` pattern match made me realize it could be consolidated a bit, looking something like this:

```
match (queue) {
  | { forwards: [], backwards: [] } => queue
  | { forwards: [head, ...ftail], backwards } => { forwards: ftail, backwards }
  ...
}
```

2020-10-04 22:03 UTC, miguelcarvalho13 commented
Oh...yeah! I think that's a good idea and it will make the code cleaner!
I'll try to work on this

2020-10-05 00:54 UTC, miguelcarvalho13 commented
@ospencer I did the changes! Seems way better than before 😁

2020-10-05 15:24 UTC, ospencer requested changes
Realized we could tidy up the tests a little bit!

And one last thing (sorry this one is annoying 🙈) could we rename `enQueue` and `deQueue` to `enqueue` and `dequeue`? I realized the Java implementation used the camel case names, but I believe these are more common since they're both just one word.

But otherwise this looks great and we'll be ready to merge after!

2020-10-05 15:24 UTC, ospencer commented on compiler/test/stdlib/queue.test.gr
> +assert Queue.isEmpty(sampleQueue) == false
```suggestion
assert Queue.isEmpty(empty)
assert !Queue.isEmpty(sampleQueue)
```

2020-10-05 15:24 UTC, ospencer commented on compiler/test/stdlib/queue.test.gr
> +assert Queue.isEmpty(Queue.deQueue(Queue.deQueue(Queue.deQueue(sampleQueue)))) == true
```suggestion
assert Queue.isEmpty(Queue.deQueue(empty))
assert Queue.isEmpty(Queue.deQueue(Queue.enQueue(1, empty)))
assert Queue.isEmpty(Queue.deQueue(Queue.deQueue(Queue.deQueue(sampleQueue))))
```

2020-10-05 20:51 UTC, miguelcarvalho13 commented on compiler/test/stdlib/queue.test.gr
> +assert Queue.isEmpty(sampleQueue) == false
Done ✅

2020-10-05 20:52 UTC, miguelcarvalho13 commented on compiler/test/stdlib/queue.test.gr
> +assert Queue.isEmpty(Queue.deQueue(Queue.deQueue(Queue.deQueue(sampleQueue)))) == true
Done ✅

2020-10-05 20:54 UTC, miguelcarvalho13 commented
> Realized we could tidy up the tests a little bit!
> 
> And one last thing (sorry this one is annoying 🙈) could we rename `enQueue` and `deQueue` to `enqueue` and `dequeue`? I realized the Java implementation used the camel case names, but I believe these are more common since they're both just one word.
> 
> But otherwise this looks great and we'll be ready to merge after!

Hahaha That's fine and it does make sense!
I did the changes let me know if there's something still missing 😄

2020-10-05 21:11 UTC, ospencer approved these changes
Perfect, thanks so much! :D

2020-10-05 21:11 UTC, merged