feat(cli): Split -g into --debug and --wat
grain-lang/grain pull request #620
Opened 2021-04-24 00:39 UTC by ospencer

This PR splits the `-g` `grainc` flag into `--debug` and `--wat`. The WebAssembly Text files produced are now named with a `.gr.wat` extension instead of `.gr.wasm.wast` to no longer use the deprecated `wast` name, and to match `.gr.wasm` <-> `.gr.wat`.

2021-04-27 01:15 UTC, phated requested changes
I think this is technically a breaking change for the CLI.

2021-04-27 06:35 UTC, ng-marcus commented
We do have the conflict with exit gracefully with -g though, so it would be good to get some version of this in so we can both debug and exit gracefully.

2021-04-27 16:12 UTC, phated commented
@ng-marcus good call. Should we mark this as a fix then? Or should we get a fix version out that removes `-g` from debug only?

2021-04-27 16:22 UTC, ng-marcus commented
@phated I'm not sure of the impact of the --wat change.  Is that breaking?

2021-05-07 12:21 UTC, follower commented on cli/bin/grain.js
> +  .graincOption("--wat", "additonally produce a WebAssembly Text (.wat) file")
Typo: "additonally" -> "additionally"

2021-05-09 20:42 UTC, ospencer commented on cli/bin/grain.js
> +  .graincOption("--wat", "additonally produce a WebAssembly Text (.wat) file")
Good catch, thanks!

2021-05-09 20:45 UTC, ospencer commented
@marcusroberts It's breaking in the sense that the flags changed and the produced files have different names.

2021-05-09 20:56 UTC, ng-marcus approved these changes

2021-05-09 20:56 UTC, ng-marcus commented
Will be good to have this in the next version then, and good to get -g back for graceful exit

2021-05-09 21:00 UTC, marcusroberts approved these changes

2021-05-15 10:47 UTC, peblair approved these changes

2021-06-03 19:20 UTC, phated approved these changes
As you ask 🔥

2021-06-03 19:20 UTC, merged