Normalise Windows paths in the JS components otherwise JSOO fails
grain-lang/grain pull request #641
Opened 2021-05-01 19:55 UTC by marcusroberts

PKGed Windows binaries fail because the specified file to compile/run is still in Windows separator style when it is parsed by the JSOO compiled component.

This fixes #640 by normalising the filename from the CLI before it is parsed

2021-05-02 16:09 UTC, peblair commented
@marcusroberts From the issue:
> @phated says " I actually think this an issue inside the compiler itself. We run Grain_utils.Files.normalize_separators on any paths we resolve internally, but probably not on the first path a user sends to the compiler. Can you look into that?"

Was that ultimately not the issue? I can understand how this change fixes the problem, but we should also (instead?) probably fix any lingering normalization issues in the compiler itself.

2021-05-02 17:18 UTC, marcusroberts commented
The compiler was fine, and if you call the compiled compiler there was no crash.

My first attempt at fixing was to use normalize_separators but it made no difference as the crash happened before that, even with those fixes in place.

The crash was in the JS compiled version only, and fixing it here has solved this problem (which was JSOO not finding the files).

I'm happy to add normalize_separators into the compiler too if you think that's helpful, but I saw no problems without it.

2021-05-02 20:20 UTC, ospencer commented on cli/bin/grain.js
> +    actions.run(actions.compile(normalised_file, program), program.opts());
We should probably have a linter, but we can change this slightly to match the file's code style:
```suggestion
    const normalisedFile = file.replace(/\\/g, "/");
    actions.run(actions.compile(normalisedFile, program), program.opts());
```

2021-05-02 20:20 UTC, ospencer commented on cli/bin/grain.js
> +    actions.compile(normalised_file, program);
```suggestion
    const normalisedFile = file.replace(/\\/g, "/");
    actions.compile(normalisedFile, program);
```

2021-05-02 20:20 UTC, ospencer commented on cli/bin/grain.js
> +    actions.lsp(normalised_file, program);
```suggestion
    const normalisedFile = file.replace(/\\/g, "/");
    actions.lsp(normalisedFile, program);
```

2021-05-02 20:20 UTC, ospencer commented on cli/bin/grain.js
> +    actions.run(normalised_wasm_file, program.opts());
```suggestion
    const normalisedWasmFile = wasmFile.replace(/\\/g, "/");
    actions.run(normalisedWasmFile, program.opts());
```

2021-05-03 18:57 UTC, phated requested changes
I'm going to do some research of my own before we merge this. I don't feel as though I have a good understanding of *where* the issue is and I don't like to add hacks when I don't.

2021-05-10 06:14 UTC, marcusroberts commented
@phated  found the root cause, so this is no longer needed.

2021-05-10 06:14 UTC, closed without merging