feat(compiler): Emit a warning when using Pervasives.(==) with unsafe Wasm types
grain-lang/grain pull request #742
Opened 2021-06-19 09:49 UTC by peblair

Closes #738.

This pull request adds a QOL improvement for low-level standard WASM development by emitting a warning when `Pervasives.(==)` is used to compare any of the following types: `WasmI32`, `WasmI64`, `WasmF32`, and `WasmF64`. This is accomplished by a new well-formedness pass on the Typed AST, which we can add things to in the future. To illustrate, consider the following `tst.gr` file:
```grain
import WasmI32 from "runtime/unsafe/wasmi32"
assert 9n == WasmI32.fromGrain(4)
assert WasmI32.toGrain(9n) == 4
let (==) = WasmI32.eq
// safe, since we have shadowed (==) with the WasmI32 variant
assert 9n == WasmI32.fromGrain(4)
```
The compiler now emits the following:
```
 λ grain git:(warn-wasm-unsafe-equal) > grain tst.gr                             
File "tst.gr", line 2, characters 7-33:
Warning 17: it looks like you are using (==) on two unsafe WASM values here.
Please ensure that this is intentional.
```

I've verified that backing out the change from #735 causes the warning to be emitted when running the test:
```
 λ grain git:(warn-wasm-unsafe-equal) ✗ > grain compiler/test/stdlib/string.test.gr
File "/Users/pblair/views/grain/stdlib/string.gr", line 1176, characters 6-22:
Warning 17: it looks like you are using (==) on two WasmI32 values here.
Please ensure that this is intentional.
```
I haven't found any warnings emitted by the standard library, which is good news in general, but bad news for #726 .

2021-06-19 16:04 UTC, ospencer requested changes

2021-06-19 16:16 UTC, ospencer commented on compiler/src/utils/warnings.re
> +  | EqualWasmUnsafe => "it looks like you are using (==) on two unsafe WASM values here.\nPlease ensure that this is intentional.";
```suggestion
  | EqualWasmUnsafe => "it looks like you are using Pervasives.(==) on two unsafe Wasm values here.\nThis is generally unsafe and will cause errors. Use `WasmI32.eq`, `WasmI64.eq`, `WasmF32.eq`, or `WasmF64.eq` instead.";
```

2021-06-20 14:23 UTC, peblair commented on compiler/src/typed/typed_well_formedness.re
> +          when Path.name(val_fullpath) == "Pervasives.==" =>
I made the change, but I'm unsure how it is less fragile. If you had something else in mind, please submit a suggestion.

2021-06-20 14:53 UTC, ospencer reviewed
Love it! I'm excited to add a warning for `print` too 😄

2021-06-20 14:53 UTC, ospencer commented on compiler/src/typed/typed_well_formedness.re
> +          when Ident.name(mod_) == "Pervasives" && fnc == "==" =>
Can simplify this a tad bit:
```suggestion
      | TExpApp(
          {
            exp_desc:
              TExpIdent(Path.PExternal(Path.PIdent({name: "Pervasives"}), "==", _), _, _),
          },
          args,
        ) =>
```

2021-06-20 14:53 UTC, ospencer commented on compiler/src/typed/typed_well_formedness.re
> +  | TTyConstr(path, _, _) => List.mem(path, wasm_unsafe_types)
🙌

2021-06-20 20:46 UTC, phated approved these changes
Heck yeah! 🥇

2021-06-22 15:17 UTC, ospencer approved these changes

2021-06-23 18:04 UTC, merged