fix(stdlib): Fixed memory leak in the print function.
grain-lang/grain pull request #770
Opened 2021-07-06 19:02 UTC by cician

This PR fixes a memory leak in the print function.

The intermediate string created was not freed. I'm not entirely sure I'm using the "right" free. Or maybe I should call decRef instead?

ps: I was using print to debug memory leaks, which lead me to the memory leak in print. So then I used print to debug the memory leak in print. 🤟

2021-07-06 19:36 UTC, ospencer requested changes
Nice find! We shouldn't need the conditional check here though. It looks like we're missing a `Memory.incRef` on line 283, and once that's in you should be able to remove the `if`. And yeah, we should use `Memory.decRef` on the ptr here instead of free 😃 

Technically `free` is fine, but `decRef` would be more correct if we were to look at `print` in isolation.

2021-07-07 10:28 UTC, peblair commented on stdlib/runtime/string.gr
> +        Memory.incRef(ptr)
I had to think about this one a bit, but I _think_ it doesn't leak memory 🙂

2021-07-07 10:28 UTC, peblair approved these changes
Great fix! Thanks!

2021-07-17 14:07 UTC, ospencer approved these changes
Thanks again @cician!

2021-07-17 14:08 UTC, merged