chore(stdlib): Add GrainDoc To Set Library
grain-lang/grain pull request #949
Opened 2021-10-01 21:25 UTC by spotandjake

chore(stdlib): Add GrainDoc To Set Library

related tp #702.

2021-11-14 10:30 UTC, marcusroberts commented on stdlib/set.gr
> + * Creates a new, empty set with an initial storage size for the given number of elements.
I’d add that this is just a best guess and doesn’t limit the size of the set which will grow anyway. 

Do we have any recommendations for making a good guess?

2021-11-14 10:32 UTC, marcusroberts commented on stdlib/set.gr
> + *
What happens if the value isn’t in the set?

2021-11-14 10:32 UTC, marcusroberts commented on stdlib/set.gr
> + * Returns a boolean indicating weather or not the set is empty.
Whether

2021-11-14 10:35 UTC, marcusroberts commented on stdlib/set.gr
> + * @param set1: The first set to merge
I’m not sure I would use merge here as that suggests union to me

2021-11-29 02:12 UTC, phated requested changes
These are looking a ton better. I made some suggestions, but I'm also trying to decide where we should be using `value` or `element` or `item` to be consistent.

2021-11-29 02:12 UTC, phated commented on stdlib/set.gr
> + * @param fn: The function used to filter the set returning `true` indicates to keep the value
```suggestion
 * @param fn: The predicate function to indicate which elements to remove from the set, where returning `false` indicates the value should be removed
```

2021-11-29 02:12 UTC, phated commented on stdlib/set.gr
> + * @param set: The set to filter
```suggestion
 * @param set: The set to iterate
```

2021-11-29 02:12 UTC, phated commented on stdlib/set.gr
> + * Removes all values that the predicate returned true for from the set.
```suggestion
 * Removes elements from a set where a predicate function returns `true`.
```

2021-11-29 02:12 UTC, phated commented on stdlib/set.gr
> + * @param fn: The function used to filter the set returning `true` indicates to remove the value
```suggestion
 * @param fn: The predicate function to indicate which elements to remove from the set, where returning `true` indicates the value should be removed
```

2021-11-29 02:12 UTC, phated commented on stdlib/set.gr
> + * @param set: The set to filter
```suggestion
 * @param set: The set to iterate
```

2021-11-29 02:12 UTC, phated commented on stdlib/set.gr
> + * Returns a list from the values of a set.
```suggestion
 * Converts a set into a list of its elements.
```

2021-11-29 02:12 UTC, phated commented on stdlib/set.gr
> + * @returns The generated List
```suggestion
 * @returns A list containing all set values
```

2021-11-29 02:12 UTC, phated commented on stdlib/set.gr
> + * @returns The generated set
```suggestion
 * @returns A set containing all list values
```

2021-11-29 02:12 UTC, phated commented on stdlib/set.gr
> + * Returns an array from the values of a set.
```suggestion
 * Converts a set into an array of its elements.
```

2021-11-29 02:12 UTC, phated commented on stdlib/set.gr
> + * @returns The generated array
```suggestion
 * @returns An array containing all set values
```

2021-11-29 02:12 UTC, phated commented on stdlib/set.gr
> + * @returns The generated set
```suggestion
 * @returns A set containing all array values
```

2021-11-29 02:12 UTC, phated commented on stdlib/set.gr
> + * @returns The generated set
```suggestion
 * @returns A set containing all items of both sets
```

2021-11-29 02:12 UTC, phated commented on stdlib/set.gr
> + * Creates a single set from the union of the given sets.
```suggestion
 * Combines two sets into a single set containing all values from both sets.
```

2021-11-29 02:12 UTC, phated commented on stdlib/set.gr
> + * @param set1: The first set to union
```suggestion
 * @param set1: The first set to combine
```

2021-11-29 02:12 UTC, phated commented on stdlib/set.gr
> + * @param set2: The second set to union
```suggestion
 * @param set2: The second set to combine
```

2021-11-29 02:12 UTC, phated commented on stdlib/set.gr
> + * Creates a set from the difference of the given sets.
```suggestion
 * Combines two sets into a single set containing only the values not shared between both sets.
```

2021-11-29 02:12 UTC, phated commented on stdlib/set.gr
> + * @returns The generated set
```suggestion
 * @param set1: The first set to combine
 * @param set2: The second set to combine
 * @returns A set containing only unshared values from both sets
```

2021-11-29 02:12 UTC, phated commented on stdlib/set.gr
> + * Creates a new set from the values that are in both set1 and set2.
```suggestion
 * Combines two sets into a single set containing only the values shared between both sets.
```

2021-11-29 02:12 UTC, phated commented on stdlib/set.gr
> + * @returns A set containing the values that are in both sets
```suggestion
 * @param set1: The first set to combine
 * @param set2: The second set to combine
 * @returns A set containing only shared values from both sets
```

2021-11-29 02:12 UTC, phated commented on stdlib/set.gr
> + * Returns a tuple representing the internal state state of the set.
```suggestion
 * Provides data representing the internal state state of the set.
```

2021-11-29 02:12 UTC, phated commented on stdlib/set.gr
> + * @param set: The set to operate on
```suggestion
 * @param set: The set to inspect
```

2021-11-29 02:12 UTC, phated commented on stdlib/set.gr
> + * @returns The internal state of the set represented as a tuple
```suggestion
 * @returns The internal state of the set
```

2021-11-29 04:16 UTC, spotandjake commented
The Changes Were Made.

2021-11-29 18:55 UTC, phated requested changes
A few more. I tried to consolidate "values" vs "elements" vs "items" by dropping "items" completely and using "values" for things going into or out-of a set and "elements" for things inside a set.

2021-11-29 18:55 UTC, phated commented on stdlib/set.gr
> + * Creates a new empty Set with an initial storage of the given length. As items are added to the Set, the length may grow or shrink. Generally, you won't need to care about the length of your set an
```suggestion
 * Creates a new empty set with an initial storage of the given length. As values are added or removed, the length may grow or shrink. Generally, you won't need to care about the length of your set and can use `Set.make()` instead.
```

2021-11-29 18:55 UTC, phated commented on stdlib/set.gr
> + * @param key: The key to search for
```suggestion
 * @param key: The value to search for
```

2021-11-29 18:55 UTC, phated commented on stdlib/set.gr
> + * @param set: The set to be searched
```suggestion
 * @param set: The set to search
```

2021-11-29 18:55 UTC, phated commented on stdlib/set.gr
> + * @returns The number of items in the set
```suggestion
 * @returns The number of elements in the set
```

2021-11-29 18:55 UTC, phated commented on stdlib/set.gr
> + * Determines if the set contains no items.
```suggestion
 * Determines if the set contains no elements.
```

2021-11-29 18:55 UTC, phated commented on stdlib/set.gr
> + * @param key: The value to add to the set
```suggestion
 * @param key: The value to add
```

2021-11-29 18:55 UTC, phated commented on stdlib/set.gr
> + * @param key: The value to remove from the set
```suggestion
 * @param key: The value to remove
```

2021-11-29 18:55 UTC, phated commented on stdlib/set.gr
> + * Combines two sets into a single set containing all values from both sets.
```suggestion
 * Combines two sets into a single set containing all elements from both sets.
```

2021-11-29 18:55 UTC, phated commented on stdlib/set.gr
> + * @returns A set containing all items of both sets
```suggestion
 * @returns A set containing all elements of both sets
```

2021-11-29 18:55 UTC, phated commented on stdlib/set.gr
> + * Combines two sets into a single set containing only the values not shared between both sets.
```suggestion
 * Combines two sets into a single set containing only the elements not shared between both sets.
```

2021-11-29 18:55 UTC, phated commented on stdlib/set.gr
> + * @returns A set containing only unshared values from both sets
```suggestion
 * @returns A set containing only unshared elements from both sets
```

2021-11-29 18:55 UTC, phated commented on stdlib/set.gr
> + * Combines two sets into a single set containing only the values shared between both sets.
```suggestion
 * Combines two sets into a single set containing only the elements shared between both sets.
```

2021-11-29 18:55 UTC, phated commented on stdlib/set.gr
> + * @returns A set containing only shared values from both sets
```suggestion
 * @returns A set containing only shared elements from both sets
```

2021-11-29 20:52 UTC, spotandjake commented
Changes Once Again Made

2021-11-29 20:57 UTC, ospencer reviewed
This looks fantastic! One tiny suggestion but otherwise thanks @spotandjake and @phated! Amazing work!

2021-11-29 20:57 UTC, ospencer commented on stdlib/set.gr
> + * Removes the given value from the set. If the value does not exist, nothing happens.
```suggestion
 * Removes the given value from the set. If the value doesn't exist, nothing happens.
```

2021-11-29 20:57 UTC, ospencer commented
Oh sorry I had some old pending stuff that you can ignore. Boo GitHub.

2021-11-29 21:00 UTC, ospencer approved these changes

2021-11-29 21:39 UTC, phated approved these changes
Absolute champion! Thanks 🥇

2021-11-29 21:40 UTC, merged